// SPDX-License-Identifier: SSPL-1.0 OR LicenseRef-Commercial

//! Multi-standard compliance metadata for CPoE evidence packets.
//!
//! Generates structured compliance annotations mapping CPoE evidence
//! to external standard identifiers and vocabularies without altering
//! the evidence itself. This module is additive — it reads evidence
//! and produces cross-references, never modifying source data.
//!
//! Standards covered:
//! - IETF RATS (draft-ietf-rats-eat, draft-ietf-rats-ear, draft-ietf-rats-ar4si)
//! - W3C DID Core 1.0 / Verifiable Credentials Data Model 2.0
//! - C2PA (ISO 19566-5, content credentials)
//! - NIST AI RMF 1.0 (AI 100-1) / NIST AI 100-4 (synthetic content)
//! - ISO/IEC 42001 (AI management systems)
//! - IPTC Digital Source Type vocabulary
//! - W3C AI Content Disclosure (proposed)
//! - WGA MBA / SAG-AFTRA AI provisions (creative rights)

use std::sync::OnceLock;

use serde::{Deserialize, Serialize};

use crate::declaration::{AiExtent, Declaration};
use crate::war::ear::{Ar4siStatus, EarToken};

// ---------------------------------------------------------------------------
// IPTC Digital Source Type URIs (used by C2PA, NIST AI 100-4, EU AI Act)
// ---------------------------------------------------------------------------

/// IPTC NewsCodes: content created entirely by a human.
pub const IPTC_HUMAN_CREATION: &str =
    "http://cv.iptc.org/newscodes/digitalsourcetype/humanCreation";

/// IPTC: content created with AI assistance but human-directed.
pub const IPTC_COMPOSITE_WITH_TRAINED_MODEL: &str =
    "http://cv.iptc.org/newscodes/digitalsourcetype/compositeWithTrainedAlgorithmicMedia";

/// IPTC: content primarily or entirely generated by a trained model.
pub const IPTC_TRAINED_ALGORITHMIC_MEDIA: &str =
    "http://cv.iptc.org/newscodes/digitalsourcetype/trainedAlgorithmicMedia";

// ---------------------------------------------------------------------------
// W3C AI Content Disclosure vocabulary (proposed CG, Feb 2026)
// ---------------------------------------------------------------------------

/// W3C AI Content Disclosure values.
///
/// Four element-level values per the W3C AI Content Disclosure CG spec,
/// plus `Mixed` for page-level `<meta>` tags when different sections
/// carry different disclosure levels.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
pub enum AiDisclosureLevel {
    /// Entirely human-authored, no AI involvement.
    #[serde(rename = "none")]
    None,
    /// Human-authored with AI assistance.
    #[serde(rename = "ai-assisted")]
    AiAssisted,
    /// Primarily or entirely AI-generated with human prompting/review.
    #[serde(rename = "ai-generated")]
    AiGenerated,
    /// AI-generated without human oversight.
    #[serde(rename = "autonomous")]
    Autonomous,
    /// Page-level only: different sections have different disclosure levels.
    /// Not valid as an element-level attribute value.
    #[serde(rename = "mixed")]
    Mixed,
}

impl AiDisclosureLevel {
    /// The W3C attribute string value for this disclosure level.
    pub fn as_str(&self) -> &'static str {
        match self {
            Self::None => "none",
            Self::AiAssisted => "ai-assisted",
            Self::AiGenerated => "ai-generated",
            Self::Autonomous => "autonomous",
            Self::Mixed => "mixed",
        }
    }

    /// Map from CPoE's `AiExtent` to W3C AI Content Disclosure level.
    ///
    /// Note: `Autonomous` and `Mixed` are never produced from `AiExtent`
    /// because CPoE's behavioral attestation inherently proves human
    /// involvement. These values exist for describing third-party content
    /// or mixed-authorship documents.
    pub fn from_ai_extent(extent: AiExtent) -> Self {
        match extent {
            AiExtent::None => Self::None,
            AiExtent::Minimal | AiExtent::Moderate => Self::AiAssisted,
            AiExtent::Substantial => Self::AiGenerated,
        }
    }

    /// Map from CPoE's declaration to IPTC Digital Source Type URI.
    pub fn to_iptc_digital_source_type(&self) -> &'static str {
        match self {
            Self::None => IPTC_HUMAN_CREATION,
            Self::AiAssisted => IPTC_COMPOSITE_WITH_TRAINED_MODEL,
            // Both AI-generated and autonomous map to the same IPTC type;
            // IPTC does not distinguish human oversight level.
            Self::AiGenerated | Self::Autonomous => IPTC_TRAINED_ALGORITHMIC_MEDIA,
            // Mixed is a document-level concept; default to composite.
            Self::Mixed => IPTC_COMPOSITE_WITH_TRAINED_MODEL,
        }
    }

    /// Map to IETF draft-abaris-aicdh `mode` token.
    pub fn to_ietf_header_mode(&self) -> &'static str {
        match self {
            Self::None => "none",
            Self::AiAssisted => "ai-modified",
            Self::AiGenerated => "ai-originated",
            Self::Autonomous => "machine-generated",
            Self::Mixed => "ai-modified",
        }
    }

    /// Generate HTML `<meta>` tag for AI content disclosure.
    pub fn to_html_meta_tag(&self) -> String {
        format!(
            r#"<meta name="ai-disclosure" content="{}">"#,
            self.as_str()
        )
    }

    /// Generate an HTML element attribute string (e.g., `ai-disclosure="ai-assisted"`).
    ///
    /// Returns `None` for `Mixed`, which is only valid as a page-level meta value.
    pub fn to_html_element_attr(&self) -> Option<String> {
        match self {
            Self::Mixed => Option::None,
            _ => Some(format!(r#"ai-disclosure="{}""#, self.as_str())),
        }
    }
}

// ---------------------------------------------------------------------------
// AI Disclosure attributes bundle (W3C companion attributes + evidence URL)
// ---------------------------------------------------------------------------

/// Complete set of W3C AI Content Disclosure attributes plus the
/// WritersProof `ai-evidence-url` extension for machine-verifiable proofs.
///
/// Can emit HTML meta tags, element-level attributes, and IETF
/// `AI-Disclosure` HTTP headers (draft-abaris-aicdh).
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct AiDisclosureAttributes {
    /// Disclosure level (none / ai-assisted / ai-generated / autonomous / mixed).
    pub level: AiDisclosureLevel,
    /// AI model identifier (e.g., `"claude-3.5-sonnet"`).
    #[serde(skip_serializing_if = "Option::is_none")]
    pub model: Option<String>,
    /// AI provider/organization (e.g., `"Anthropic"`).
    #[serde(skip_serializing_if = "Option::is_none")]
    pub provider: Option<String>,
    /// URL to prompt methodology documentation.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub prompt_url: Option<String>,
    /// WritersProof evidence verification URL
    /// (e.g., `https://writersproof.com/verify/{proof_id}`).
    #[serde(skip_serializing_if = "Option::is_none")]
    pub evidence_url: Option<String>,
}

impl AiDisclosureAttributes {
    /// Create attributes from a disclosure level with no companion metadata.
    pub fn from_level(level: AiDisclosureLevel) -> Self {
        Self {
            level,
            model: Option::None,
            provider: Option::None,
            prompt_url: Option::None,
            evidence_url: Option::None,
        }
    }

    /// Create attributes from a CPoE declaration and optional evidence URL.
    pub fn from_declaration(decl: &Declaration, evidence_url: Option<String>) -> Self {
        let level = AiDisclosureLevel::from_ai_extent(decl.max_ai_extent());
        let (model, provider) = decl.ai_tools.first().map_or(
            (Option::None, Option::None),
            |t| (Some(t.tool.clone()), t.version.clone()),
        );
        Self {
            level,
            model,
            provider,
            prompt_url: Option::None,
            evidence_url,
        }
    }

    /// Generate all HTML `<meta>` tags for page-level disclosure.
    ///
    /// Produces the primary `ai-disclosure` meta tag plus optional
    /// companion tags for model, provider, prompt URL, and evidence URL.
    pub fn to_html_meta_tags(&self) -> String {
        let mut tags = vec![self.level.to_html_meta_tag()];

        if let Some(ref model) = self.model {
            tags.push(format!(
                r#"<meta name="ai-model" content="{}">"#,
                html_escape_attr(model)
            ));
        }
        if let Some(ref provider) = self.provider {
            tags.push(format!(
                r#"<meta name="ai-provider" content="{}">"#,
                html_escape_attr(provider)
            ));
        }
        if let Some(ref prompt_url) = self.prompt_url {
            tags.push(format!(
                r#"<meta name="ai-prompt-url" content="{}">"#,
                html_escape_attr(prompt_url)
            ));
        }
        if let Some(ref evidence_url) = self.evidence_url {
            tags.push(format!(
                r#"<meta name="ai-evidence-url" content="{}">"#,
                html_escape_attr(evidence_url)
            ));
        }

        tags.join("\n")
    }

    /// Generate HTML element-level attribute string.
    ///
    /// Returns a space-separated set of attributes suitable for embedding
    /// in an HTML element tag. Returns `None` if the level is `Mixed`
    /// (which is only valid at page level).
    pub fn to_html_element_attrs(&self) -> Option<String> {
        if self.level == AiDisclosureLevel::Mixed {
            return Option::None;
        }

        let mut attrs = vec![format!(r#"ai-disclosure="{}""#, self.level.as_str())];

        if let Some(ref model) = self.model {
            attrs.push(format!(r#"ai-model="{}""#, html_escape_attr(model)));
        }
        if let Some(ref provider) = self.provider {
            attrs.push(format!(
                r#"ai-provider="{}""#,
                html_escape_attr(provider)
            ));
        }
        if let Some(ref prompt_url) = self.prompt_url {
            attrs.push(format!(
                r#"ai-prompt-url="{}""#,
                html_escape_attr(prompt_url)
            ));
        }
        if let Some(ref evidence_url) = self.evidence_url {
            attrs.push(format!(
                r#"ai-evidence-url="{}""#,
                html_escape_attr(evidence_url)
            ));
        }

        Some(attrs.join(" "))
    }

    /// Generate an IETF `AI-Disclosure` HTTP header value per draft-abaris-aicdh.
    ///
    /// Format: `mode=<token>; model="<string>"; provider="<string>"; date=@<epoch>`
    pub fn to_ietf_header(&self) -> String {
        let mut parts = vec![format!("mode={}", self.level.to_ietf_header_mode())];

        if let Some(ref model) = self.model {
            parts.push(format!(r#"model="{}""#, model));
        }
        if let Some(ref provider) = self.provider {
            parts.push(format!(r#"provider="{}""#, provider));
        }

        parts.join("; ")
    }
}

/// Minimal HTML attribute value escaping for double-quoted contexts.
fn html_escape_attr(s: &str) -> String {
    s.replace('&', "&amp;")
        .replace('"', "&quot;")
        .replace('<', "&lt;")
        .replace('>', "&gt;")
}

// ---------------------------------------------------------------------------
// NIST AI RMF 1.0 subcategory mapping
// ---------------------------------------------------------------------------

/// NIST AI RMF 1.0 subcategories that CPoE evidence addresses.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct NistRmfMapping {
    /// Subcategory identifiers addressed (e.g., "GV-1.1", "MS-2.6").
    pub subcategories: Vec<NistSubcategory>,
}

/// A single NIST AI RMF subcategory with CPoE's coverage status.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct NistSubcategory {
    /// Subcategory ID (e.g., "GV-1.2").
    pub id: String,
    /// Short description from the RMF.
    pub description: String,
    /// How CPoE addresses this subcategory.
    pub cpoe_coverage: String,
}

/// Generate the NIST AI RMF mapping for a CPoE evidence packet.
static NIST_RMF: OnceLock<NistRmfMapping> = OnceLock::new();

pub fn nist_rmf_mapping() -> &'static NistRmfMapping {
    NIST_RMF.get_or_init(|| {
    NistRmfMapping {
        subcategories: vec![
            NistSubcategory {
                id: "GV-1.1".into(),
                description: "Legal and regulatory requirements documented".into(),
                cpoe_coverage: "Evidence packets carry declaration with AI disclosure fields per EU AI Act Article 50".into(),
            },
            NistSubcategory {
                id: "GV-1.2".into(),
                description: "Trustworthiness characteristics integrated".into(),
                cpoe_coverage: "AR4SI trustworthiness vector maps 8 components per draft-ietf-rats-ar4si".into(),
            },
            NistSubcategory {
                id: "MS-2.6".into(),
                description: "AI system performance assessed".into(),
                cpoe_coverage: "Forensic analysis produces assessment_score with 5 verdict levels".into(),
            },
            NistSubcategory {
                id: "MS-2.11".into(),
                description: "Fairness assessed and documented".into(),
                cpoe_coverage: "Behavioral analysis uses biological plausibility ranges, not demographic profiling".into(),
            },
            NistSubcategory {
                id: "MG-4.1".into(),
                description: "Post-deployment monitoring procedures".into(),
                cpoe_coverage: "Continuous sentinel monitoring with checkpoint chain for lifecycle tracking".into(),
            },
        ],
    }
    })
}

// ---------------------------------------------------------------------------
// ISO/IEC 42001 Annex A control mapping
// ---------------------------------------------------------------------------

/// ISO/IEC 42001 Annex A controls relevant to CPoE.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Iso42001Mapping {
    pub controls: Vec<Iso42001Control>,
}

/// A single ISO 42001 Annex A control with CPoE coverage.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Iso42001Control {
    pub id: String,
    pub topic: String,
    pub cpoe_coverage: String,
}

/// Generate the ISO 42001 mapping for CPoE.
static ISO_42001: OnceLock<Iso42001Mapping> = OnceLock::new();

pub fn iso_42001_mapping() -> &'static Iso42001Mapping {
    ISO_42001.get_or_init(|| {
    Iso42001Mapping {
        controls: vec![
            Iso42001Control {
                id: "A.6".into(),
                topic: "Data governance".into(),
                cpoe_coverage: "Evidence data integrity via HMAC chains, WAL, and MMR append-only proofs".into(),
            },
            Iso42001Control {
                id: "A.7".into(),
                topic: "System information documentation".into(),
                cpoe_coverage: "Evidence packets include claim_generator_info with version, capabilities, limitations".into(),
            },
            Iso42001Control {
                id: "A.8".into(),
                topic: "Information for interested parties (transparency)".into(),
                cpoe_coverage: "Forensic verdict with confidence, anomaly counts, per-checkpoint flags, and limitations array".into(),
            },
            Iso42001Control {
                id: "A.10".into(),
                topic: "Accountability and responsibility".into(),
                cpoe_coverage: "Key hierarchy with master→session→ratchet chain ties actions to signing identity".into(),
            },
        ],
    }
    })
}

// ---------------------------------------------------------------------------
// WGA MBA / SAG-AFTRA creative rights compliance
// ---------------------------------------------------------------------------

/// Creative rights compliance status derived from a CPoE declaration.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct CreativeRightsCompliance {
    /// Whether the content is attested as human-authored.
    pub human_authored: bool,
    /// Whether GAI source material is disclosed per WGA MBA Section 72.
    pub gai_source_disclosed: bool,
    /// AI disclosure level per the declaration.
    pub ai_disclosure: AiDisclosureLevel,
    /// IPTC Digital Source Type URI.
    pub digital_source_type: String,
    /// Whether the attestation satisfies WGA MBA human authorship requirements.
    pub wga_mba_compliant: bool,
    /// Notes on compliance gaps.
    pub notes: Vec<String>,
}

/// Derive creative rights compliance from a declaration and EAR token.
pub fn creative_rights_compliance(
    declaration: Option<&Declaration>,
    ear: Option<&EarToken>,
) -> CreativeRightsCompliance {
    let mut notes = Vec::new();

    let (ai_disclosure, gai_source_disclosed) = if let Some(decl) = declaration {
        let max_extent = decl.max_ai_extent();
        // Check GAI disclosure before moving max_extent
        let no_ai = matches!(max_extent, AiExtent::None);
        let disclosure = AiDisclosureLevel::from_ai_extent(max_extent);

        // WGA MBA requires disclosure of any GAI-generated source material.
        // Currently, max_ai_extent() derives from ai_tools, so if tools are
        // listed then disclosure is inherent. A future `ai_used_undisclosed`
        // field on Declaration would allow detecting the gap explicitly.
        let gai_disclosed = no_ai || !decl.ai_tools.is_empty();

        (disclosure, gai_disclosed)
    } else {
        notes.push("No declaration present — cannot verify AI disclosure".into());
        (AiDisclosureLevel::None, false)
    };

    // Check EAR verdict for human authorship attestation strength
    let human_authored = if let Some(ear) = ear {
        if let Some(appr) = ear.pop_appraisal() {
            matches!(
                appr.ear_status,
                Ar4siStatus::Affirming | Ar4siStatus::Warning
            )
        } else {
            false
        }
    } else {
        false
    };

    if !human_authored {
        notes.push(
            "EAR appraisal does not affirm human authorship — WGA compliance uncertain".into(),
        );
    }

    let wga_mba_compliant =
        human_authored && gai_source_disclosed && ai_disclosure != AiDisclosureLevel::AiGenerated;

    CreativeRightsCompliance {
        human_authored,
        gai_source_disclosed,
        ai_disclosure,
        digital_source_type: ai_disclosure.to_iptc_digital_source_type().to_string(),
        wga_mba_compliant,
        notes,
    }
}

// ---------------------------------------------------------------------------
// Unified standards compliance report
// ---------------------------------------------------------------------------

/// Comprehensive standards compliance report for a CPoE evidence packet.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct StandardsComplianceReport {
    /// IETF RATS alignment.
    pub rats: RatsAlignment,
    /// W3C DID method used for author identity.
    pub did_method: Option<String>,
    /// AI content disclosure level (W3C CG proposed).
    pub ai_disclosure: AiDisclosureLevel,
    /// IPTC Digital Source Type URI.
    pub iptc_digital_source_type: String,
    /// C2PA assertion label.
    pub c2pa_assertion_label: String,
    /// Creative rights compliance (WGA/SAG-AFTRA).
    pub creative_rights: CreativeRightsCompliance,
    /// NIST AI RMF subcategories addressed.
    pub nist_rmf: NistRmfMapping,
    /// ISO 42001 controls addressed.
    pub iso_42001: Iso42001Mapping,
}

/// IETF RATS alignment summary.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct RatsAlignment {
    /// EAT profile URI.
    pub eat_profile: String,
    /// EAR status.
    pub ear_status: String,
    /// Whether AR4SI trust vector is present.
    pub has_trust_vector: bool,
    /// Whether the appraisal follows draft-ietf-rats-ear.
    pub ear_compliant: bool,
}

/// Generate a full standards compliance report.
pub fn standards_compliance_report(
    declaration: Option<&Declaration>,
    ear: Option<&EarToken>,
    author_did: Option<&str>,
) -> StandardsComplianceReport {
    let rats = if let Some(ear) = ear {
        RatsAlignment {
            eat_profile: ear.eat_profile.clone(),
            ear_status: ear
                .pop_appraisal()
                .map(|a| a.ear_status.as_str().to_owned())
                .unwrap_or_else(|| "unknown".to_string()),
            has_trust_vector: ear
                .pop_appraisal()
                .and_then(|a| a.ear_trustworthiness_vector.as_ref())
                .is_some(),
            ear_compliant: true,
        }
    } else {
        RatsAlignment {
            eat_profile: String::new(),
            ear_status: "none".into(),
            has_trust_vector: false,
            ear_compliant: false,
        }
    };

    let ai_disclosure = declaration
        .map(|d| AiDisclosureLevel::from_ai_extent(d.max_ai_extent()))
        .unwrap_or(AiDisclosureLevel::None);

    let creative_rights = creative_rights_compliance(declaration, ear);

    StandardsComplianceReport {
        rats,
        // Extract DID method: "did:key:z6Mk..." -> "did:key"
        did_method: author_did.map(|d| {
            let parts: Vec<&str> = d.splitn(3, ':').collect();
            if parts.len() >= 2 {
                format!("{}:{}", parts[0], parts[1])
            } else {
                d.to_string()
            }
        }),
        ai_disclosure,
        iptc_digital_source_type: ai_disclosure.to_iptc_digital_source_type().to_string(),
        c2pa_assertion_label: super::c2pa::ASSERTION_LABEL.to_string(),
        creative_rights,
        nist_rmf: nist_rmf_mapping().clone(),
        iso_42001: iso_42001_mapping().clone(),
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_ai_disclosure_none() {
        let level = AiDisclosureLevel::from_ai_extent(AiExtent::None);
        assert_eq!(level, AiDisclosureLevel::None);
        assert_eq!(level.to_iptc_digital_source_type(), IPTC_HUMAN_CREATION);
    }

    #[test]
    fn test_ai_disclosure_minimal() {
        let level = AiDisclosureLevel::from_ai_extent(AiExtent::Minimal);
        assert_eq!(level, AiDisclosureLevel::AiAssisted);
        assert_eq!(
            level.to_iptc_digital_source_type(),
            IPTC_COMPOSITE_WITH_TRAINED_MODEL
        );
    }

    #[test]
    fn test_ai_disclosure_substantial() {
        let level = AiDisclosureLevel::from_ai_extent(AiExtent::Substantial);
        assert_eq!(level, AiDisclosureLevel::AiGenerated);
        assert_eq!(
            level.to_iptc_digital_source_type(),
            IPTC_TRAINED_ALGORITHMIC_MEDIA
        );
    }

    #[test]
    fn test_html_meta_tag() {
        assert_eq!(
            AiDisclosureLevel::None.to_html_meta_tag(),
            r#"<meta name="ai-disclosure" content="none">"#
        );
        assert_eq!(
            AiDisclosureLevel::AiAssisted.to_html_meta_tag(),
            r#"<meta name="ai-disclosure" content="ai-assisted">"#
        );
    }

    #[test]
    fn test_nist_rmf_mapping_has_entries() {
        let mapping = nist_rmf_mapping();
        assert!(!mapping.subcategories.is_empty());
        assert!(mapping.subcategories.iter().any(|s| s.id == "GV-1.2"));
    }

    #[test]
    fn test_iso_42001_mapping_has_a8() {
        let mapping = iso_42001_mapping();
        assert!(mapping.controls.iter().any(|c| c.id == "A.8"));
    }

    #[test]
    fn test_creative_rights_no_declaration() {
        let result = creative_rights_compliance(None, None);
        assert!(!result.human_authored);
        assert!(!result.wga_mba_compliant);
        assert!(!result.notes.is_empty());
    }

    #[test]
    fn test_autonomous_level() {
        let level = AiDisclosureLevel::Autonomous;
        assert_eq!(level.as_str(), "autonomous");
        assert_eq!(
            level.to_iptc_digital_source_type(),
            IPTC_TRAINED_ALGORITHMIC_MEDIA
        );
        assert_eq!(level.to_ietf_header_mode(), "machine-generated");
        assert_eq!(
            level.to_html_meta_tag(),
            r#"<meta name="ai-disclosure" content="autonomous">"#
        );
        assert_eq!(
            level.to_html_element_attr(),
            Some(r#"ai-disclosure="autonomous""#.to_string())
        );
    }

    #[test]
    fn test_mixed_level_page_only() {
        let level = AiDisclosureLevel::Mixed;
        assert_eq!(level.as_str(), "mixed");
        assert_eq!(
            level.to_html_meta_tag(),
            r#"<meta name="ai-disclosure" content="mixed">"#
        );
        // Mixed is not valid as an element-level attribute.
        assert!(level.to_html_element_attr().is_none());
    }

    #[test]
    fn test_ietf_header_modes() {
        assert_eq!(AiDisclosureLevel::None.to_ietf_header_mode(), "none");
        assert_eq!(
            AiDisclosureLevel::AiAssisted.to_ietf_header_mode(),
            "ai-modified"
        );
        assert_eq!(
            AiDisclosureLevel::AiGenerated.to_ietf_header_mode(),
            "ai-originated"
        );
    }

    #[test]
    fn test_disclosure_attributes_meta_tags() {
        let attrs = AiDisclosureAttributes {
            level: AiDisclosureLevel::AiAssisted,
            model: Some("claude-3.5-sonnet".into()),
            provider: Some("Anthropic".into()),
            prompt_url: None,
            evidence_url: Some("https://writersproof.com/verify/abc123".into()),
        };
        let html = attrs.to_html_meta_tags();
        assert!(html.contains(r#"<meta name="ai-disclosure" content="ai-assisted">"#));
        assert!(html.contains(r#"<meta name="ai-model" content="claude-3.5-sonnet">"#));
        assert!(html.contains(r#"<meta name="ai-provider" content="Anthropic">"#));
        assert!(!html.contains("ai-prompt-url"));
        assert!(html.contains(
            r#"<meta name="ai-evidence-url" content="https://writersproof.com/verify/abc123">"#
        ));
    }

    #[test]
    fn test_disclosure_attributes_element_attrs() {
        let attrs = AiDisclosureAttributes {
            level: AiDisclosureLevel::None,
            model: None,
            provider: None,
            prompt_url: None,
            evidence_url: Some("https://writersproof.com/verify/xyz".into()),
        };
        let attr_str = attrs.to_html_element_attrs().expect("not mixed");
        assert!(attr_str.contains(r#"ai-disclosure="none""#));
        assert!(attr_str.contains(r#"ai-evidence-url="https://writersproof.com/verify/xyz""#));
        assert!(!attr_str.contains("ai-model"));
    }

    #[test]
    fn test_disclosure_attributes_mixed_no_element() {
        let attrs = AiDisclosureAttributes::from_level(AiDisclosureLevel::Mixed);
        assert!(attrs.to_html_element_attrs().is_none());
    }

    #[test]
    fn test_disclosure_attributes_ietf_header() {
        let attrs = AiDisclosureAttributes {
            level: AiDisclosureLevel::AiGenerated,
            model: Some("gpt-4".into()),
            provider: Some("OpenAI".into()),
            prompt_url: None,
            evidence_url: None,
        };
        let header = attrs.to_ietf_header();
        assert_eq!(header, r#"mode=ai-originated; model="gpt-4"; provider="OpenAI""#);
    }

    #[test]
    fn test_disclosure_attributes_ietf_header_minimal() {
        let attrs = AiDisclosureAttributes::from_level(AiDisclosureLevel::None);
        assert_eq!(attrs.to_ietf_header(), "mode=none");
    }

    #[test]
    fn test_html_escape_in_attributes() {
        let attrs = AiDisclosureAttributes {
            level: AiDisclosureLevel::AiAssisted,
            model: Some(r#"model"with<special>&chars"#.into()),
            provider: None,
            prompt_url: None,
            evidence_url: None,
        };
        let html = attrs.to_html_meta_tags();
        assert!(html.contains("&amp;"));
        assert!(html.contains("&quot;"));
        assert!(html.contains("&lt;"));
        assert!(html.contains("&gt;"));
    }

    #[test]
    fn test_serde_roundtrip_new_variants() {
        let autonomous: AiDisclosureLevel =
            serde_json::from_str(r#""autonomous""#).expect("deserialize");
        assert_eq!(autonomous, AiDisclosureLevel::Autonomous);

        let mixed: AiDisclosureLevel =
            serde_json::from_str(r#""mixed""#).expect("deserialize");
        assert_eq!(mixed, AiDisclosureLevel::Mixed);

        assert_eq!(
            serde_json::to_string(&AiDisclosureLevel::Autonomous).expect("serialize"),
            r#""autonomous""#
        );
    }
}
